### ISSUE TITLE
oygan mealludan

### ISSUE THREAD

**Issue by david-sterling** [breogann/UAX-activities#1]
me jale el notibuk pero se como aser para ejecutiarlo en la compu grasias de antebraso

**Comment by breogann** [comment]
¡Hola David! 

Tienes dos formas: manual y a través de git.

- La forma manual: clicar en el botón verde, descargar como zip. 
- Clonando el repositorio: Para esto te hará falta tener git instalado. Una vez instalado y autorizado, podrías hacer un git clone con la URL del repositorio. 

La primera opción es la más sencilla :)
